name: Lint the sourcecode

on:
  
  pull_request:
    branches:    
      - dev
      - main
  workflow_dispatch:

permissions:
  contents: write

env:
  SRC_DIR: src

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
      - name: setup
        run: |
          pip install .[linting]
      - name: run black
        run: |
          black "$SRC_DIR" --check
      - name: run isort
        run: |
          isort "$SRC_DIR"/**/*.py -m 3 --trailing-comma -c
      - name: run pylint
        run: |
          pylint "$SRC_DIR" --fail-under=8

