name: Lint the sourcecode

on:
  
  pull_request:
    branches:    
      - dev
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Python Linter
        uses: sunnysid3up/python-linter@master
        with:
          source: "src"
